### ISSUE TITLE
avatar of enzuru question

### ISSUE THREAD

**Issue by CapSel** [enzuru/home#1]
I'm curious as to where did this photo came from.
It seems to be undecorated (no gold crown attached to it, etc) photo from "miraculous painting" from nearby church.

**Comment by enzuru** [comment]
My avatar is an unvarnished depiction of the [Black Madonna of Częstochowa](https://en.wikipedia.org/wiki/Black_Madonna_of_Cz%C4%99stochowa). I found the image here: https://en.wikipedia.org/wiki/Black_Madonna

**Comment by CapSel** [comment]
Cool. Thanks to you I found out that there are several copies of this painting - one in nearby church :)

**Comment by enzuru** [comment]
@CapSel hopefully one day I can visit it in person myself.
